### ISSUE TITLE
No 'version' key in the manifest file for custom integration 'gecko'

### ISSUE THREAD

**Issue by brewston** [gazoodle/gecko-home-assistant#10]
I noticed this in the logs today :

`2021-03-10 17:07:07 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'gecko'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'gecko'`

**Comment by gazoodle** [comment]
Thanks for the spot. I'm working on another project at the moment, but I'll try to get this fixed soon so that it doesn't break HA.

**Comment by brewston** [comment]
I _think_ it would probably be as simple as adding :

`"version": "1.0",`

 into : 

https://github.com/gazoodle/gecko-home-assistant/blob/master/custom_components/gecko/manifest.json

let me add that line manually on my installation to see if if fixes the error

**Comment by brewston** [comment]
Yeah, just dropping that in there work for me. I created a pull request with the change. Hope I did it right, it's the first one I've done on github

**Comment by gazoodle** [comment]
@brewston fixed, thanks!
