### ISSUE TITLE
Microsoft Azure based IP attempting connection to hot tub multiple times every second, UDP Port 10022

### ISSUE THREAD

**Issue by briandye** [gazoodle/gecko-home-assistant#103]
Anyone else seeing anything like this? Wondering if the HA integration is in play here or just Gecko being chatty. Only noticed it since it's in common port range of VoIP ports and my firewall keeps blocking it.

**Comment by gazoodle** [comment]
There is no cloud code in either the integration or the protocol library, so this must be something to do with either the in.touch2 app or the Gecko dealer app (they have a way to help most spa users remotely without having to do a site visit, so perhaps that's what's going on here)
