### ISSUE TITLE
Getting error when adding new Spa to v0.1.9

### ISSUE THREAD

**Issue by itorront** [gazoodle/gecko-home-assistant#104]
Hi,
We just received our new spa with the in.touch2 control and i went to add the Gecko integration from HACS and received this error when it tries to initialize the connection to the spa and errors.

**ERROR (MainThread) [geckolib.async_spa] Cannot find GeckoConfigStruct module for inYT v84**

Here are my verisons for HA:
Core - 2024.6.2
Supervisor - 2024.06.0
Operating System - 12.3
Frontend - 20240610.0

Gazoodle Gecko integration - v0.1.9

Everything for the in.touch2 app has been setup and i have my water care setup with a different schedule than it recommends.

Thanks!

**Comment by gazoodle** [comment]
Ought to be fixed with v0.1.11 as the pack structures have been updated
