### ISSUE TITLE
Thermostat not full compatible with Google 

### ISSUE THREAD

**Issue by marcoboutch** [gazoodle/gecko-home-assistant#12]
Hi, first, thank for this really nice addon.

When i add this climate sensor on google home i can't change temperature or ask to google current temperature. Climate sensor look standard but i dont know what is option google not like. Im sorry i speak english little bit. I know i can add Gecko direct to google home but i cant use because work only in english language.... Thank you :)
![Screenshot_20210311-234056](https://user-images.githubusercontent.com/60036848/110893669-6be06100-82c4-11eb-8274-81ee72c7b38e.png)
![Screenshot_20210311-234115](https://user-images.githubusercontent.com/60036848/110893670-6be06100-82c4-11eb-8a84-b60a291f4c49.png)

**Comment by gazoodle** [comment]
I think this will be down to the fact that the custom component only contains resources for English, and it's probably not using the resources correctly at present. Thanks for the spot, I'll get onto this as soon as I've got to a natural break in another project I'm working on at the moment

**Comment by marcoboutch** [comment]
Yes i understand, the life is too short to do all project, family, etc ;)

I not found the real issue but i can bypass this problem when i create virtual climate sensor (standard) and sync temperature and target value. Is not sexy but work good for now... i can just set temperature from google home now but is ok for my use. Thank you again.

**Comment by marcoboutch** [comment]
Just for info, i realise a have an orther problem anyway. Google Home not support up to 32C for normal Thermostat. :\

**Comment by marcoboutch** [comment]
Ohhhh, the bar cant set more of 32C but from voice work good :)

**Comment by marcoboutch** [comment]
Hi gazoodle ,

i not see paypal donation link on your github. If you want add... :) Thank you

**Comment by gazoodle** [comment]
Sounds like this is an issue with HA climate controls in Google rather than this integration. If you think this isn't the case, please re-open it.
