### ISSUE TITLE
Fahrenheit instead of Celcius

### ISSUE THREAD

**Issue by mcfarlde** [gazoodle/gecko-home-assistant#16]
Any chance we could have selection for which units to use?

**Comment by rct** [comment]
This might be a stale issue,  I'm seeing Fahrenheit not Celsius on my installation.

I believe Home Assistant does thelocalization conversion for things where it knows the class is temperature (or other units that need conversion).  I'm in the US, my Home Assistant is localizing temperatures correctly for me even though I have sensors that are sending Celsius values with the unit indicated.

**Comment by mcfarlde** [comment]
rct, thanks.
