### ISSUE TITLE
Some errors in log

### ISSUE THREAD

**Issue by sicarriere** [gazoodle/gecko-home-assistant#2]
Thanks @gazoodle for the "alpha" integration.

Here some errors in HA logs :

`Logger: homeassistant.util.async_
Source: util/async_.py:105
First occurred: 9:54:09 (1 occurrences)
Last logged: 9:54:09

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for gecko doing I/O at custom_components/gecko/__init__.py, line 47: facade = locator.get_spa_from_identifier(spa_identifier).get_facade(False)`

`Logger: geckolib.driver.udp_socket
Source: /usr/local/lib/python3.8/site-packages/geckolib/driver/udp_socket.py:316
First occurred: 9:54:17 (17 occurrences)
Last logged: 10:04:31

Couldn't find new handler for b"STATV\t\n'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
Couldn't find new handler for b"STATV\n\x0b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
Couldn't find new handler for b"STATV\x0b\x0c'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
Couldn't find new handler for b'STATV\x0c\x00\x0b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'
Couldn't find new handler for b'PACKS'`

`Logger: geckolib.driver.spastruct
Source: /usr/local/lib/python3.8/site-packages/geckolib/driver/spastruct.py:49
First occurred: 9:54:19 (46 occurrences)
Last logged: 10:09:39

Out-of-sequence status block segment 8 - ignored
Out-of-sequence status block segment 9 - ignored
Out-of-sequence status block segment 10 - ignored
Out-of-sequence status block segment 11 - ignored
Out-of-sequence status block segment 12 - ignored`

`Logger: geckolib.driver.spastruct
Source: /usr/local/lib/python3.8/site-packages/geckolib/driver/spastruct.py:53
First occurred: 9:54:22 (5 occurrences)
Last logged: 10:09:39

Retry status block request`

The version of GeckoLib is 0.3.17 that was installed when I installed the integration via HACS

Also, the Pump is set as a switch, so unable to see/set the Speed of it (you know, I have a 2 speed pump). So maybe set Pump as a "Fan" instead of a "Switch"?

**Comment by gazoodle** [comment]
Thanks! I’ll look into the I/O during init.

Pumps: I’ve not implemented multi speed yet, but representing as a fan was the way I was planning on going!

**Comment by Abtsbergblick** [comment]
Thank you Gazoodle, found your HA addons for gecko intouch2. Much welcomed! Installation worked fine (HA runs on Odroid N2+), also intergration shows up the relevant parameters from the spa.

Several entries in the HA logfile show up:
1.
Logger: homeassistant.util.async_
Source: util/async_.py:105
First occurred: 22. Dezember 2020, 18:59:43 (1 occurrences)
Last logged: 22. Dezember 2020, 18:59:43
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for gecko doing I/O at custom_components/gecko/__init__.py, line 45: facade = locator.get_spa_from_identifier(spa_identifier).get_facade(False) 

2.
Logger: geckolib.driver.spastruct
Source: /usr/local/lib/python3.8/site-packages/geckolib/driver/spastruct.py:49
First occurred: 22. Dezember 2020, 19:00:01 (444 occurrences)
Last logged: 07:28:49
    Out-of-sequence status block segment 8 - ignored
    Out-of-sequence status block segment 9 - ignored
    Out-of-sequence status block segment 10 - ignored
    Out-of-sequence status block segment 11 - ignored
    Out-of-sequence status block segment 12 - ignored

3.
Logger: geckolib.driver.spastruct
Source: /usr/local/lib/python3.8/site-packages/geckolib/driver/spastruct.py:53
First occurred: 22. Dezember 2020, 19:00:03 (63 occurrences)
Last logged: 07:28:49
Retry status block request

**Comment by gazoodle** [comment]
All these issues should be resolved now
