### ISSUE TITLE
Erratic current temperature and other entities (Geckolib STATP handling error)

### ISSUE THREAD

**Issue by rct** [gazoodle/gecko-home-assistant#22]
## Version of the custom_component

0.0.5 - manifest.json
0.0.1 - const.py

(Geckolib version 0.3.17)

## Describe the bug

The current temperature reported through the Home Assistant climate device can show erratic changes due to a bug in GeckoLib's 0.3.17's handling of partial status updates. See https://github.com/gazoodle/geckolib/issues/20. 

(While this is a problem that needs to be resolved in Geckolib and therefore doesn't belong here, I'm opening this issue to help the Home Assistant users find and work around this issue until the problem in Geckolib is fixed.

## Description

Splitting the discussion of this issue from #15 into a separate dedicated issue thread.

> 
> ![image](https://user-images.githubusercontent.com/38770/121788390-ed34e180-cb9a-11eb-9960-903edc94f1af.png)
> 
> The red line (current temperature) keeps briefly returning to the original starting value, because there is a bug in the way partial status updates are applied. Old processed updates aren't being cleared out and keep being reprocessed. This was discovered by @maegibbons in https://github.com/gazoodle/geckolib/issues/20

Working around this requires patching Geckolib's `spa.py`.  Will try to add some instructions for patching below.

----

**EDIT -- putting these instructions here for now, will integrate above later**

## Using a local copy of Geckolib

To use a local copy of Geckolib that will survive container updates.

1. Put a copy of `src/geckolib` from the Geckolib repo under `/config/geckolib`, 
2. Remove the requirements line that mentions `geckolib` from `custom_components/gecko/manifest.json`. 

Note to remember it is there when Geckolib gets updated (or the custom component gets integrated)

---- 

## using an updated Geckolib from GitHub

Alternate that I haven't tested from Hass dev docs,  Change `manifest.json` to point to a specific GitHub repo/branch: 

See https://developers.home-assistant.io/docs/creating_integration_manifest#custom-requirements-during-development--testing 

`https://developers.home-assistant.io/docs/creating_integration_manifest#custom-requirements-during-development--testing`

This would probably be more useful to anyone that isn't doing any hacking on `Geckolib`, but does introduce a dependency on GitHub.

**Comment by rct** [comment]
Dumb Home Assistant question for @maegibbons or anyone applying patches to Geckolib:

Where/how are you making changes to Geckolib?

Are you editing the files in the home assistant container (knowing that the edits won't survive the container being updated)?

Or are you pulling a copy of Geckolib into `custom_components`?

If the later, what's the right directory structure for that?

Do you also remove Geckolib from manifest.json?

**Comment by maegibbons** [comment]
You need to edit them in the home assistant directory.

They get overwritten with each HA docker update.  So i run a script run by pyscript that copies the patched versions that i store a copy of in the /config  directory back to the main driver files under /usr/lib

**Comment by rct** [comment]
> You need to edit them in the home assistant docker directory under /usr/lib

There is a way to pull the code for the module into the `custom_component/...` directory, so that it will be used by import instead of fetching the module form PyPi. I just haven't done it in a long time, so I don't remember the directory structure needed.

You may also need to edit the custom component's `manifest.json` to remove the Geckolib dependency (so it doesn't try to fetch it from PyPi.)

I don't feel like doing trial and error on that now.  I guess I should probably bite the bullet and try setting up a development environment.

**Comment by maegibbons** [comment]
Not tried that.  Went the enable developer access route to get to /usr/lib

**Comment by maegibbons** [comment]
If you want i can let you have the script and the amended spa.py file that you can place in config directory tomorrow.

You need to install pyscript

**Comment by maegibbons** [comment]
I have posted this at: https://github.com/gazoodle/geckolib/issues/20#issuecomment-860126803

**Comment by rct** [comment]
Moving more stuff here - Other entities may also update erratically

![image](https://user-images.githubusercontent.com/38770/121813623-d776f900-cc3a-11eb-8941-e5aa3d87b2cd.png)

This "stuttering" of on/off is hopefully resolved with that patch.
![image](https://user-images.githubusercontent.com/38770/121813797-ac40d980-cc3b-11eb-8d25-8b35e03d6d90.png)

**Comment by gazoodle** [comment]
Can you confirm this is fixed in v0.0.7 and then close this issue?

Thanks

**Comment by rct** [comment]
Will do in the next few days. (I'm away right now, will upgrade to the latest custom component and revert to current geckolib from pypi)

**Comment by gazoodle** [comment]
I think this is resolved now.
