### ISSUE TITLE
Do you want me to add an all-in-one GitHub action?

### ISSUE THREAD

**Issue by KTibow** [gazoodle/gecko-home-assistant#3]
**Is your feature request related to a problem? Please describe.**
Right now, I see that you're using an integration blueprint. It has some pretty good CI, but I can add an all-in-one GitHub action, which has a bit more stuff (actually format instead of just checking, also run isort as well as black, also run wemake-python-styleguide).

**Describe the solution you'd like**
If you want, I can add some advanced CI to your repo in a PR. Let me know if you want that.
- Do you want to enable auto-formatting on push with comment amending?
- Do you want packaged or independent (I recommend packaged because I can send updates)?

**Describe alternatives you've considered**
Keep it as it is.

**Additional context**
https://github.com/KTibow/ha-blueprint

**Comment by gazoodle** [comment]
Sure, why not? Go ahead and create a PR.

Thanks
