### ISSUE TITLE
Set RGB lights to a specific setting

### ISSUE THREAD

**Issue by ralphjohnson** [gazoodle/gecko-home-assistant#34]
My hot tub supports about 8 different colours, and a setting to cycle through them all.  My preferred colour is about 5 or 6 colours in, and the only way to get to it is by turning the lights on, and then off 5 or 6 times in quick succession.  This is the same on either the panel, or through this API.  I'm not sure if it's even possible, but it would be fantastic to go straight to my preferred colour rather than having to cycle through them!  Have I missed anything in the API, or is there any way to do this I've not considered?

**Comment by RhinoRich** [comment]
I think you've covered it. It's a toggle command but there's no handshake when the command is issued. The status will update (on or off), so you can check if it received the command, but not where it is in the sequence. I did try to do it with node red but the variable lag from the module made it unreliable.

**Comment by ralphjohnson** [comment]
Thanks for looking!
