### ISSUE TITLE
Gecko unit is not responsive 

### ISSUE THREAD

**Issue by Johan-Arens** [gazoodle/gecko-home-assistant#35]
Hello folks

Not probably the right forum for that, but am I the only one to experience some instabilities with the gecko unit ? 
Every 5 to 6 days, I have to power-cycle it, even the native IOS app doesn't work when the unit looks to be frozen, not only HA. 

Let me know, thanks ! 

Johan

**Comment by gazoodle** [comment]
For what it's worth, I had an intermittent problem similar to this where the in.touch module plugged into my switch couldn't talk to the spa unit. I moved it to a slightly closer place and it's no longer doing that. Maybe try that?
