### ISSUE TITLE
Allow pointing at static IP

### ISSUE THREAD

**Issue by coolacid** [gazoodle/gecko-home-assistant#37]
**Is your feature request related to a problem? Please describe.**
My HA system sits in a docker container on a different VLAN from all my IoT devices. Thus, the automatic detection won't work.

**Describe the solution you'd like**
I'd love to see both the upstream library, and this module support adding the integration - then the integration can either search for tubs, and/or allow for a static IP address to be used. 

**Describe alternatives you've considered**
I'm not sure what alternative I'd be able to get away with. At best, I might be able to write a python proxy that would also run on the container network that just pipes the requests to the correct IP address.

**Additional context**
None. 

Thanks for both the Library and the Module.

**Comment by coolacid** [comment]
So, after reading the code, I was able to successfully connect to my Spa using a static IP from a different network. 

`locator = GeckoLocator(CLIENT_ID, static_ip="[IP]")`

So, in reality, this feature request only requires support for static IP, instead of discovery.

**Comment by coolacid** [comment]
Work around: 
Add the static_ip setting to the GeckoLocator in `config_flow.py` and `__init__.py`

**Comment by remiks** [comment]
@coolacid You mind sharing how and where you added which line?

**Comment by LordAttilas** [comment]
Same issue for me. My Geckos controller is on a static IP isolated in a IoT VLAN.

Would be great to have a standard way to provide the IP inside Home Assistant GUI to loosing custom modification of source code.

Many thanks for creating that integration !

@coolacid Thanks for sharing the temporary fix 👍

**Comment by gazoodle** [comment]
v0.0.8 should fix this

**Comment by llamafilm** [comment]
I have the same issue with a separated IoT VLAN.  Where am I supposed to enter the static IP in gecko config?
