### ISSUE TITLE
Deal with CI warnings

### ISSUE THREAD

**Issue by gazoodle** [gazoodle/gecko-home-assistant#41]
CI gives this report 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! ha-blueprint is being retired, it has way too many issues with it !
! please manually use hassfest and hacs in actions, ping @KTibow if you want help !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Opening this so that I can ask @KTibow to give appropriate pointers -- Thanks!

**Comment by KTibow** [comment]
I can send over a pull request quickly. Do you use the CI for anything else, like `flake8`?

**Comment by gazoodle** [comment]
Don’t think so. It’s pretty much out of the box from your original I think.

**Comment by KTibow** [comment]
I mean, what do you get out of the CI other than a failure/success?

**Comment by gazoodle** [comment]
Formatting I think. But TBH I accepted your original pull req late 2020 and I respond to any issues that get thrown up after checkin when the workflow runs. 

I should probably take some time to investigate how that all hangs together. The CI seems to refer to KTibow/ha-blueprint@stable FWIW.
