### ISSUE TITLE
Spa not identified: inyt spa pack

### ISSUE THREAD

**Issue by eranjo** [gazoodle/gecko-home-assistant#5]
## Version of the custom_component

Latest available version

## Configuration

```yaml

Add your logs here.

```

## Describe the bug
Not able to connect my inyt spa pack.

## Debug log

```text

Logger: custom_components.gecko
Source: custom_components/gecko/__init__.py:49 
Integration: Gecko (documentation, issues) 
First occurred: 8:24:09 PM (1 occurrences) 
Last logged: 8:24:09 PM

Exception during entry setup
Traceback (most recent call last):
  File "/config/custom_components/gecko/__init__.py", line 49, in async_setup_entry
    while not facade.is_connected:
  File "/usr/local/lib/python3.8/site-packages/geckolib/automation/facade.py", line 68, in is_connected
    if not self._spa.is_connected:
  File "/usr/local/lib/python3.8/site-packages/geckolib/spa.py", line 306, in is_connected
    raise RuntimeError("Spa took too long to connect ...")
RuntimeError: Spa took too long to connect ...

```

**Comment by eranjo** [comment]
Installing the custom component there's SpaPackStruct.xml installed in HA's Config folder. I then replaced this file with my own xml file pulled using the the instructions here https://github.com/gazoodle/geckolib/issues/12.

Then deleted the custom component and reinstalled it...and found my spa successfully with 10 entities :)


My Spa: Circulating Pump
binary_sensor.my_spa_circulating_pump
Gecko

My Spa: Filter Status:Clean
binary_sensor.my_spa_filter_status_clean
Gecko

My Spa: Filter Status:Purge
binary_sensor.my_spa_filter_status_purge
Gecko

My Spa: Heater
climate.my_spa_heater
Gecko

My Spa: Lights
light.my_spa_lights
Gecko

My Spa: Ozone
binary_sensor.my_spa_ozone
Gecko

My Spa: Pump 1
switch.my_spa_pump_1
Gecko

My Spa: Pump 2
switch.my_spa_pump_2
Gecko

My Spa: Smart Winter Mode:Active
binary_sensor.my_spa_smart_winter_mode_active
Gecko

My Spa: Smart Winter Mode:Risk
sensor.my_spa_smart_winter_mode_risk
Gecko

**Comment by NorthernMunkey** [comment]
would you be able to share your XML file?
