### ISSUE TITLE
Feature request - virtual energy sensors

### ISSUE THREAD

**Issue by brewston** [gazoodle/gecko-home-assistant#50]
**Is your feature request related to a problem? Please describe.**

Unable to monitor tub energy usage

**Describe the solution you'd like**

I found this integration - https://github.com/bramstroker/homeassistant-powercalc

I set up sensors for my tub heater and pump (lo/hi) I estimated their respective power draw by checking my smart meter when they were on/off. I wonder if some of that code could be re-used in this integration ?

**Describe alternatives you've considered**
You can set up the virtual power sensors separately using the integration mentioned. It doesn't _have_ to be part of this one.

**Additional context**
Even if this can't be integrated, I thought people might be interested to know about powercalc for tub energy monitoring.

**Comment by maegibbons** [comment]
Cannot really see that this should be part of this integration which should only deal with the standard gecko hardware components.  Power consumption should be done accurately with a CT clamp.

**Comment by GSpivey1** [comment]
I got an emporia power monitor to calculate power usage on everything in my power panel,, including hot tub

**Comment by maegibbons** [comment]
That's what I use.  It can also be flashed with ESPhome making it more integrated with HA.

**Comment by gazoodle** [comment]
Closing this to tidy the issues list up. I agree with @maegibbons that this is outside the remit of the integration.
