### ISSUE TITLE
Initial setup in HA vs Simulator

### ISSUE THREAD

**Issue by darglo** [gazoodle/gecko-home-assistant#57]
Hi Gazoodle! Thanks for creating the component.

Unfortunately, I do not get it working in my HA setup (newest HA version). It does not discover the SPA, I just get one visual component called "Gecko Update", and nothing else is discovered.

I did check your geckolib project and run the commands in the shell on the same host the HA is running, and I am able to see the SPA being discovered and giving correct output with temp. etc in the python console.

I tried to installed HA on raspberryPI on docker, doing all setup with hacs and your repo there, and the result is the same. Currently, HA is running on VM, new setup, same behaviour. I got latest version from GitHub both on main and latest release branch.

Logging enabled, not producing any logs for Gecko component.

Unless this is related ?

00:55:11 – (FEL) /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py - Meddelandet inträffade först 00:54:18 och har hänt 2 gånger

Thanks for any advice, 
Dariusz

**Comment by gazoodle** [comment]
> 00:55:11 – (FEL) /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py - Meddelandet inträffade först 00:54:18 och har hänt 2 gånger

I don't think that is related, the web_protocol.py is not used by the geckolib library.

Did you try using the specific IP address to try to discover the spa that way?

**Comment by mf76130** [comment]
hi,
i am having the same issue.
Fresh HA, fresh HACS, latest Gecko plugin and i only see the update function.
And i had half a year ago a working setup. So its not the Gecko Hardware.
Do you think it might be a DNS issue?

br
Michael

**Comment by mf76130** [comment]
i did connect via terminal and using GeckoShell.run, that shows me the name IP and all looks correct.
![image](https://user-images.githubusercontent.com/653889/170477442-e9e3755b-e447-4b0f-93e8-aef54831aae9.png)

**Comment by mf76130** [comment]
ok, i found the reason:
On HA 8 when you install Gecko it automatic adds the Gecko update to the integrations, but you still need to add the integration to have it fully available

**Comment by darglo** [comment]
> hi, i am having the same issue. Fresh HA, fresh HACS, latest Gecko plugin and i only see the update function. And i had half a year ago a working setup. So its not the Gecko Hardware. Do you think it might be a DNS issue?
> 
> br Michael

Great it was not just me:)

**Comment by darglo** [comment]
> ok, i found the reason: On HA 8 when you install Gecko it automatic adds the Gecko update to the integrations, but you still need to add the integration to have it fully available

Cool, I will give it a go first with the shell. Can you explain a little bit more what do you mean by "still need to add the integration to have it fully available" ? On the list of devices in hacs, I get only gecko update, so not sure what else could I add.

thanks for helping and sharing

**Comment by darglo** [comment]
> > 00:55:11 – (FEL) /usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py - Meddelandet inträffade först 00:54:18 och har hänt 2 gånger
> 
> I don't think that is related, the web_protocol.py is not used by the geckolib library.
> 
> Did you try using the specific IP address to try to discover the spa that way?

Thanks for your reply, I will try a shell first as mf76130 suggested.

**Comment by darglo** [comment]
I tried with the gecko shell on that raspberry pi I am running HA.

It discovers it without problems.

![IMG_5184](https://user-images.githubusercontent.com/6041999/170569442-52a99285-25c8-467f-8a6a-5d190ca91ced.JPEG)

But in GUI, just Gecko Update.

mf76130 I would appreciate your help with claryfying how did you manage do add the rest of the sensors of gecko - for me is just this gecko.update that is available.

Thanks in advance!

**Comment by mf76130** [comment]
You just go to "Settings" - "Devices & Services", click on "Add Integration" and there search for "Gecko", click it and follow the setup.

**Comment by darglo** [comment]
Thanks for advice. Well, I was adding other integrations from HACS this week and this extra step was not required that's why I even did not try to do that. It works now as expected.
