### ISSUE TITLE
Make radio sensor easier to use in graphs and automations

### ISSUE THREAD

**Issue by rct** [gazoodle/gecko-home-assistant#59]
**Is your feature request related to a problem? Please describe.**
The current radio sensor is combing two values into one as a string that makes graphing and creating automations more difficult.

**Describe the solution you'd like**
Break the signal level and channel number into different entities.

Signal level should be a number with a unit of measurement that allows it to be easily graphed in Home Assistant using the built in support for numeric entities.

Channel number is probably more of an attribute than a separate entity, It should rarely change.

For either entity consider using the  `"entity_category": "diagnostic"` feasture so that it doesn't get added to the dashboard.

**Describe alternatives you've considered**
(I haven't thought of any)

**Additional context**
discussion in issue https://github.com/gazoodle/gecko-home-assistant/issues/58

**Comment by gazoodle** [comment]
Fixed in v0.1.9
