### ISSUE TITLE
Weird late night temperature change

### ISSUE THREAD

**Issue by JohnMcLear** [gazoodle/gecko-home-assistant#61]
At 2am this morning my target temperature changed from 38.5 degs to 32

I leave the tub in "Away from Home".  I have had this config in place for weeks working fine.

Running latest HASS and Plugin.

I can't seem to see what made the temperature change, obviously I can write an automation to keep it as per the target temp but I wondered if there is a common/known issue w/ the plugin changing the temp?

Potentially a change from the tub itself?

Very strange!

**Comment by gazoodle** [comment]
Agreed, it's very odd!

I've just been back through the code and I don't see where it could have been adjusted like that. Does this happen regularly or was that a one-off? It sounds like the tub but why it would choose to do that a 2am is beyond me.

**Comment by JohnMcLear** [comment]
It did it again a few days ago.  I wish there was a way in HA I can see what's making the change, it's as if it's coming from the UI but none of my users are aware of making the change:

![image](https://user-images.githubusercontent.com/220864/175937793-c7a13a61-43d6-44cc-bc54-185a4710d488.png)

I guess one thing to test is to uninstall the HA app for a week or so and see if it persists?  Is no one else expecting a similar behaviour?

**Comment by hazymat** [comment]
Hi John, did you get further with testing this? I would be interested to know the outcome.

**Comment by JohnMcLear** [comment]
Hot tubs currently off for Winter.  It'll come back on in a month or so and then I'll continue testing :)

**Comment by gazoodle** [comment]
I'm closing this as there doesn't appear to be any further info on this. Please reopen if it recurs.

**Comment by JohnMcLear** [comment]
Just to confirm, I haven't seen this behaviour since.  Thanks for keeping this issue open for me to help debug.
