### ISSUE TITLE
Last ping sensor floods the log/history as it seems to ping every 2 seconds

### ISSUE THREAD

**Issue by joggs** [gazoodle/gecko-home-assistant#64]
**Is your feature request related to a problem? Please describe.**
"Last ping" sensor floods the log and history as it seems to ping every 2 seconds. It would be nice to lower the ping frequency or customize it. For me every 60 seconds or 5 minutes would be enough, but I'm not aware of how others are using this sensor.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gazoodle** [comment]
Fixed in v0.1.9
