### ISSUE TITLE
Temperature sensor in Farenheight

### ISSUE THREAD

**Issue by eaglex01** [gazoodle/gecko-home-assistant#66]
Hi,

Would it be possible to have the option to chose to get the temperature either in celcius or farenheight?

that would make my life so much easier.

thanks

**Comment by gazoodle** [comment]
Sadly not. The choice of temperature unit is controlled by Home Assistant. Any attempt to return the other unit will result in the UI simply converting it to the system default. See [Settings > System > General](https://my.home-assistant.io/redirect/general).
