### ISSUE TITLE
No entities found

### ISSUE THREAD

**Issue by mikeboiko** [gazoodle/gecko-home-assistant#7]
## Version of the custom_component

Version 0.0.1
git commit 2d3e2d7

## Configuration

I'm running a dockerized version of home assistant using host networking.
Added the gecko custom_component as documented.

## Describe the bug

I integrated the gecko custom component and used the Integrations UI to add Gecko. The process seemed to run successfully from the front end, but no entities were exposed after the component was added. Although it does seem like my spa was discovered.

![image](https://user-images.githubusercontent.com/24229496/104970966-7d834780-59aa-11eb-80f8-ae655d34f587.png)

## Debug log

This is my docker log

```text

home-assistant    | 2021-01-18 16:20:02 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for gecko doing I/O at custom_components/gecko/__init__.py, line 45: facade = locator.get_spa_from_identifier(spa_identifier).get_facade(False)
home-assistant    | 2021-01-18 16:20:04 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\x01\x02'\x08\x03\x00\x00\x00\x00\x00\x00\x00\x01\x00\x11\x00\x010\x14x\xf0\x02\x14\x02\x04\x02\x00\x00\x00s\x01\x0e\x02\xd0\x00\x00\x04\x01\x00\x00\x01\x00"
home-assistant    | 2021-01-18 16:20:04 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\x01\x02'\x08\x03\x00\x00\x00\x00\x00\x00\x00\x01\x00\x11\x00\x010\x14x\xf0\x02\x14\x02\x04\x02\x00\x00\x00s\x01\x0e\x02\xd0\x00\x00\x04\x01\x00\x00\x01\x00"
home-assistant    | 2021-01-18 16:20:04 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\x02\x03'\x00\x0f\x02\xc5\x00\x02\x00\x02\x01\x01\x03\x03\x03\x05\x05\x04\x04\x01\x03\x06\x14\x0f\x18\x0f\x0f\x14\x06\x06\x06\x06\x06\x06\x00\x00\x00\x00\x01\x00\x00"
home-assistant    | 2021-01-18 16:20:04 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\x03\x04'\x00\x14\x00x\x00\n @\x80\x02\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
home-assistant    | 2021-01-18 16:20:04 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\x04\x05'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
home-assistant    | 2021-01-18 16:20:04 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\x05\x06'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
home-assistant    | 2021-01-18 16:20:04 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\x06\x07'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x05\x00\x00\x00\x00\x00\x02\x0f\xff\xff\xff"
home-assistant    | 2021-01-18 16:20:04 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\x07\x08'\x00\x00\x02\xc7\x02\xc7\x00\x00\x00\x00\x00\x00\x00@\n\x00\nK\x00=%\x00<;\x01b\x01\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\n"
home-assistant    | 2021-01-18 16:20:04 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\x08\t'\x8c\x00\x00\x00\x00\x02\xcc\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
home-assistant    | 2021-01-18 16:20:05 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\t\n'\x00\x00\x00\x00\x01B\x08\x00\x18\x0f\x00\x00\x00\x00vT\x00\x00\x00\x00\x11\x0e\x1e\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
home-assistant    | 2021-01-18 16:20:05 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\n\x0b'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00"
home-assistant    | 2021-01-18 16:20:05 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\x0b\x0c'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff"
home-assistant    | 2021-01-18 16:20:05 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b"STATV\x0c\r'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xffinYT_C60.xml\x00\x00\x00\x00inYT_S59.xm"
home-assistant    | 2021-01-18 16:20:05 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b'STATV\r\x00\x05l\x00\x00\x00\x00'
home-assistant    | 2021-01-18 16:20:09 WARNING (Thread-16) [geckolib.driver.udp_socket] Couldn't find new handler for b'FILES,inYT_C60.xml,inYT_S59.xml'
home-assistant    | 2021-01-18 16:20:33 ERROR (Thread-15) [root] Uncaught thread exception
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
home-assistant    |     self.run()
home-assistant    |   File "/usr/local/lib/python3.8/threading.py", line 870, in run
home-assistant    |     self._target(*self._args, **self._kwargs)
home-assistant    |   File "/usr/local/lib/python3.8/site-packages/geckolib/spa.py", line 282, in _ping_thread_func
home-assistant    |     self.refresh()
home-assistant    |   File "/usr/local/lib/python3.8/site-packages/geckolib/spa.py", line 311, in refresh
home-assistant    |     if not self.is_connected:
home-assistant    |   File "/usr/local/lib/python3.8/site-packages/geckolib/spa.py", line 306, in is_connected
home-assistant    |     raise RuntimeError("Spa took too long to connect ...")
home-assistant    | RuntimeError: Spa took too long to connect ...
home-assistant    | 2021-01-18 16:20:33 ERROR (MainThread) [custom_components.gecko] Exception during entry setup
home-assistant    | Traceback (most recent call last):
home-assistant    |   File "/config/custom_components/gecko/__init__.py", line 47, in async_setup_entry
home-assistant    |     while not facade.is_connected:
home-assistant    |   File "/usr/local/lib/python3.8/site-packages/geckolib/automation/facade.py", line 68, in is_connected
home-assistant    |     if not self._spa.is_connected:
home-assistant    |   File "/usr/local/lib/python3.8/site-packages/geckolib/spa.py", line 306, in is_connected
home-assistant    |     raise RuntimeError("Spa took too long to connect ...")
home-assistant    | RuntimeError: Spa took too long to connect ...
```

FYI - I have been using this library for several months to log hot tub data: https://github.com/chicago6061/in.touch2

Let me know if what additional details you require from me.

Thank you so much for making this component! Looking forward to integrating my spa with HA.

**Comment by mikeboiko** [comment]
Actually, I just tried again and it worked!
![image](https://user-images.githubusercontent.com/24229496/104971560-66455980-59ac-11eb-9df7-98750fc01a38.png)
![image](https://user-images.githubusercontent.com/24229496/104971587-778e6600-59ac-11eb-9ed9-8e5538f5e29e.png)
I think my other script was connected to the spa at the same time and I've noticed it doesn't allow more than one simultaneous connection.
I'm closing this issue.

**Comment by sicarriere** [comment]
I think, if I remembered, that the two script are using the same UUID. So the In.Touch2 module doesn’t know where to talk back! In my HA Dev, I changed the UUID for this integration. But I still have some error in the log.

**Comment by mikeboiko** [comment]
Ahh yea that makes sense. I can't with 100% certainty that the issue was due to my other script, but I'm pretty sure that was the case.

**Comment by gazoodle** [comment]
Re-opening as memory jogger to generate new GUID each time the Gecko component is installed in HA.

**Comment by mikeboiko** [comment]
> Re-opening as memory jogger to generate new GUID each time the Gecko component is installed in HA.

Oh nice, good plan.
I'm loving the plugin btw! I would love to contribute to it, and fix some bugs related to my specific spa. Do you have any development environment notes you could share with me please?

**Comment by simonhoole** [comment]
HI,  I am new to HA and I am having the problem with not showing the entities.  I dont understand what you have done to resolve the matter.  Any chance of helping and doing a dummies / easier explanation.  Sorry and thank you

**Comment by mikeboiko** [comment]
> 
> 
> HI, I am new to HA and I am having the problem with not showing the entities. I dont understand what you have done to resolve the matter. Any chance of helping and doing a dummies / easier explanation. Sorry and thank you

I simply re-tried adding the integration while making sure that I wasn't accessing the spa with any other apps.

**Comment by simonhoole** [comment]
Hi. Thanks for that. So did u delete your apps on ur phone etc. Or did you just make sure that they were not connected to the spa at the time of re adding. Thanks

Regards

Simon Hoole
Mobile 07843 411234
________________________________

**Comment by simonhoole** [comment]
> > HI, I am new to HA and I am having the problem with not showing the entities. I dont understand what you have done to resolve the matter. Any chance of helping and doing a dummies / easier explanation. Sorry and thank you
> 
> I simply re-tried adding the integration while making sure that I wasn't accessing the spa with any other apps.

Ok thanks. Did u delete ur apps or did u just make sure that they were not connected.

**Comment by mikeboiko** [comment]
> > > HI, I am new to HA and I am having the problem with not showing the entities. I dont understand what you have done to resolve the matter. Any chance of helping and doing a dummies / easier explanation. Sorry and thank you
> > 
> > 
> > I simply re-tried adding the integration while making sure that I wasn't accessing the spa with any other apps.
> 
> Ok thanks. Did u delete ur apps or did u just make sure that they were not connected.

I didn't delete any apps. Just made sure they were not connected.

**Comment by BachaSport** [comment]
Hey,

same issue here, i canot find any entites despite addon canging spa name along changes to the app on the phone. Any ideas?

**Comment by orangelizard** [comment]
Same issue here, spa is discovered correctly but no entitys created. No other devices (phones tablets etc) connected, spa hub restarted.

**Comment by gazoodle** [comment]
v0.0.8 should fix this
