### ISSUE TITLE
Warning in logs about breaking change coming in HA 2023.3. 

### ISSUE THREAD

**Issue by arimorcos** [gazoodle/gecko-home-assistant#76]
Warning in logs suggesting there's a breaking change coming in 2023.3. 

`Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for gecko using this method at custom_components/gecko/spa_manager.py, line 98: self.hass.config_entries.async_setup_platforms(self.entry, self.platforms)`

**Comment by PhAzE-Variance** [comment]
Do you have this working on 2023.2?

**Comment by arimorcos** [comment]
Yes, it is still working in 2023.2.1

**Comment by gazoodle** [comment]
Fixed in v0.1.9
