### ISSUE TITLE
2 Speed pump

### ISSUE THREAD

**Issue by mikeboiko** [gazoodle/gecko-home-assistant#8]
My "pump 1" has 2 speed options.
When I click on the pump in the official intouch.2 app, it turns on the pump in slow mode.
When I click on the pump again, it changes it to fast mode.
When I click the pump a 3rd time, it turns off.

It seems that the "pump 1" home assistant switch operates in a similar way. It's a little bit confusing though. When the switch is already on (pump running slow) and I go to toggle the switch off, it turns itself back on (pump running fast). Now that I understand this operation, I'm ok with this.

However, I'm wondering if we could expose a binary sensor that shows whether the pump is in slow/fast mode please? Or perhaps it would be best to have a 3 state switch of sorts?

**Comment by gazoodle** [comment]
Version v0.0.7 ought to handle this now
