### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jamesocar** [gazoodle/gecko-home-assistant#90]
I've installed via HACS v 1.9 but only see the "Update" configuration on the Gecko device screen.
I had expected to have to configure an IP address at least for my Gecko but I wasn't prompted for anything on installation.

I've tried installing a couple of times, including v 1.8 but still get the same results.

**Comment by proggaras** [comment]
If you go to: Settings => Devices & services => ADD INTEGRATION you can search for Gecko. After clicking this screen should appear: 
![gecko_ip](https://github.com/gazoodle/gecko-home-assistant/assets/9094312/c59e5313-528f-423c-8650-871d9f96819d)

**Comment by gazoodle** [comment]
Closed as @proggaras has answered this.
