### ISSUE TITLE
Error in logs about issues with HA 2025 release...

### ISSUE THREAD

**Issue by Racerider101** [gazoodle/gecko-home-assistant#96]
Hello
I'm a novice here and don;t understand if this is going to be an issue or not or when it will become an issue.  Any help advice much appreciated and apols if already covered and I've not spotted it.  thx

Logger: homeassistant.helpers.entity
Source: helpers/entity.py:1567
First occurred: 3:10:52 PM (4 occurrences)
Last logged: 3:10:52 PM

Entity None (<class 'custom_components.gecko.fan.GeckoFan'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <FanEntityFeature.PRESET_MODE: 8>, please create a bug report at https://github.com/gazoodle/gecko-home-assistant/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
Entity None (<class 'custom_components.gecko.climate.GeckoClimate'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <ClimateEntityFeature.TARGET_TEMPERATURE|PRESET_MODE: 17>, please create a bug report at https://github.com/gazoodle/gecko-home-assistant/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation

**Comment by BenJewell** [comment]
This won't be an actual issue until the beginning of 2025.

Not sure if anyone is still maintaining this addon, but it should be an easy fix when the time gets closer.

**Comment by gazoodle** [comment]
Ought to be fixed with v0.1.10
